<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\View\Element\Template;
use Scandiweb\MenuOrganizer\ViewModel\MenuManager;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var MenuManager $viewModelMenuManager */
$viewModelMenuManager = $viewModels->require(MenuManager::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$uniqueId = '_' . uniqid();

$menuItems = $viewModelMenuManager->getMenuItems('menu');

$block->setData('cache_tags', $viewModelMenuManager->getIdentities());

?>
<div x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
     class="z-20 navigation hidden lg:flex"
>
    <!-- desktop -->
    <div x-ref="nav-desktop"
         @load.window="setActiveMenu($root)"
         class="hidden lg:block lg:relative lg:min-h-0 lg:px-8 lg:w-auto lg:pt-0">
        <nav
            class="w-full duration-150 ease-in-out transform flex justify-start
            w-auto relative min-h-0 transition-display"
        >
            <?php foreach ($menuItems as $index => $menuItem): ?>
                <div class="relative mr-2 level-0"
                     @mouseenter="hoverPanelActiveId = '<?= /* @noEscape */ (string) $index ?>'"
                     @mouseleave="hoverPanelActiveId = 0"
                >
                    <span class="flex items-center block p-3 text-md bg-opacity-95">
                        <a class="w-full py-3 text-base text-gray-700 hover:underline level-0"
                           href="<?= $escaper->escapeUrl($menuItem->getFullUrl()) ?>"
                           title="<?= $escaper->escapeHtmlAttr($menuItem->getTitle()) ?>"
                        >
                            <?= $escaper->escapeHtml($menuItem->getTitle()) ?>
                        </a>
                    </span>
                    <?php if ($menuItem->hasChildren()): ?>
                        <div
                            class="absolute z-10 hidden px-6 py-4 -ml-6 shadow-lg bg-container-lighter/95"
                            :class="{
                                'hidden' : hoverPanelActiveId !== '<?= /* @noEscape */ (string) $index ?>',
                                'block' : hoverPanelActiveId === '<?= /* @noEscape */ (string) $index ?>'
                            }">
                            <?php foreach ($menuItem->getChildren() as $subMenuItem): ?>
                                <a href="<?= $escaper->escapeUrl($subMenuItem->getFullUrl()) ?>"
                                   title="<?= $escaper->escapeHtmlAttr($subMenuItem->getTitle()) ?>"
                                   class="block w-full px-3 py-1 my-1 whitespace-nowrap first:mt-0 hover:underline"
                                >
                                    <span class="text-base text-gray-700">
                                        <?= $escaper->escapeHtml($subMenuItem->getTitle()) ?>
                                    </span>
                                </a>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </nav>
    </div>
</div>
<script>
    'use strict';

    const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            hoverPanelActiveId: null,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.classList.add('underline');
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').querySelector('a.level-0').classList.add('underline');
                });
            }
        }
    }
</script>
