<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$imageUrl1 = "https://unsplash.com/photos/v0f_sspLB-o/download?force=true&w=664&q=80";
// Or, get an image from `web/images/` in your theme:
// $imageUrl1 = $escaper->escapeHtmlAttr($block->getViewFileUrl('images/banner.jpg'))

$imageUrl2 = "https://unsplash.com/photos/dCL6vpW8oJM/download?force=true&w=664&q=80";
$imageUrl3 = "https://unsplash.com/photos/SdmdP3UKE6g/download?force=true&w=664&q=80";
$imageUrl4 = "https://unsplash.com/photos/2mGaIs51MNU/download?force=true&w=664&q=80";
?>
<script>
    function carousel() {
        return {
            container: null,
            next: null,
            first: null,
            speed: 5000, // set to 0 to disable
            slidePage: true, // set to false for sliding one item at the time, true for the whole visible set

            init() {
                this.container = this.$refs.container
                this.first = this.container.firstElementChild;

                this.update();
                this.container.addEventListener('scroll', this.update.bind(this), {passive: true});
                if(this.speed > 0){
                    this.start();
                }
            },
            start() {
                let sliderTimer = setInterval(() => this.scrollToNextOrFirst() , this.speed);
            },
            update() {
                const rect = this.container.getBoundingClientRect();

                const visibleElements = Array.from(this.container.children).filter((child) => {
                    const childRect = child.getBoundingClientRect();
                    return childRect.left >= Math.floor(rect.left) && Math.floor(childRect.right) <= rect.right;
                });

                if (visibleElements.length > 0) {
                    this.next = this.getNextElement(visibleElements);
                }
            },
            getNextElement(list) {
                const lastElementIsVisible = !(list[list.length - 1].nextElementSibling instanceof HTMLElement);

                const sibling = (this.slidePage)
                    ? list[list.length - 1].nextElementSibling
                    : ((lastElementIsVisible)
                        ? null
                        : list[0].nextElementSibling);

                return (sibling instanceof HTMLElement) ? sibling : null;
            },
            scrollToNextOrFirst() {
                (this.next !== null)? this.scrollTo(this.next) : this.scrollTo(this.first);
            },
            scrollTo(element) {
                const current = this.container;
                if (!current || !element) return;
                const nextScrollPosition = element.offsetLeft;

                current.scroll({
                    left: nextScrollPosition,
                    behavior: 'smooth',
                });
            }
        };
    }
</script>

<div class="my-20">
    <div class="flex-wrap flex justify-between items-baseline mb-7">
        <div class="text-3xl leading-9 font-bold mr-1">
            Shop by category
        </div>
        <a
            href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
            class="block text-lg leading-7 font-semibold text-blue-700"
        >
            Browse all →
        </a>
    </div>

    <div x-data="carousel()" class="relative overflow-hidden">
        <div x-ref="container" class="snap gap-3 flex overflow-x-scroll">

            <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="w-[calc(45%-6px)] h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600px]
                       flex-auto grow-0 shrink-0 block shadow-lg rounded-md overflow-hidden relative"
            >
                <img
                    alt="A woman stretching after a run"
                    class="absolute w-full h-full object-cover"
                    src="<?= $escaper->escapeHtmlAttr($imageUrl1) ?>"
                    width="664"
                    height="996"
                    loading="lazy"
                />
                <div class="absolute bottom-0 pt-9 pb-6 px-6 text-center text-xl leading-10 font-bold uppercase w-full
                            text-white drop-shadow-lg bg-gradient-to-b from-transparent to-gray-800
                            sm:text-2xl md:text-3xl lg:text-4xl"
                >
                    Women
                </div>
            </a>

            <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="w-[calc(45%-6px)] h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600px]
                       flex-auto grow-0 shrink-0 block shadow-lg rounded-md overflow-hidden relative"
            >
                <img
                    alt="A man in a hoodie and cap walking away"
                    class="absolute w-full h-full object-cover"
                    src="<?= $escaper->escapeHtmlAttr($imageUrl2) ?>"
                    width="664"
                    height="996"
                    loading="lazy"
                />
                <div class="absolute bottom-0 pt-9 pb-6 px-6 text-center text-xl leading-10 font-bold uppercase w-full
                            text-white drop-shadow-lg bg-gradient-to-b from-transparent to-gray-800
                            sm:text-2xl md:text-3xl lg:text-4xl"
                >
                    Men
                </div>
            </a>

            <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="w-[calc(45%-6px)] h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600px]
                       flex-auto grow-0 shrink-0 block shadow-lg rounded-md overflow-hidden relative"
            >
                <img
                    alt="A woman showing her sports watch"
                    class="absolute w-full h-full object-cover"
                    src="<?= $escaper->escapeHtmlAttr($imageUrl3) ?>"
                    width="664"
                    height="996"
                    loading="lazy"
                />
                <div
                    class="absolute bottom-0 pt-9 pb-6 px-6 text-center text-xl leading-10 font-bold uppercase w-full
                           text-white drop-shadow-lg bg-gradient-to-b from-transparent to-gray-800
                           sm:text-2xl md:text-3xl lg:text-4xl"
                >
                    Gear
                </div>
            </a>

            <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="w-[calc(45%-6px)] h-[300px] sm:h-[400px] md:h-[500px] lg:h-[600px]
                      flex-auto grow-0 shrink-0 block shadow-lg rounded-md overflow-hidden relative"
            >
                <img
                    alt="A woman making a knee kick in the air"
                    class="absolute w-full h-full object-cover"
                    src="<?= $escaper->escapeHtmlAttr($imageUrl4) ?>"
                    width="664"
                    height="996"
                    loading="lazy"
                />
                <div
                    class="absolute bottom-0 pt-9 pb-6 px-6 text-center text-xl leading-10 font-bold uppercase w-full
                           text-white drop-shadow-lg bg-gradient-to-b from-transparent to-gray-800
                           sm:text-2xl md:text-3xl lg:text-4xl"
                >
                    Training
                </div>
            </a>

        </div>
    </div>
</div>
