<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<style>
    .bg-wiggle {
        background-image: url("data:image/svg+xml,%3Csvg width='52' height='26' viewBox='0 0 52 26' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23f472b6' fill-opacity='1'%3E%3Cpath d='M10 10c0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6h2c0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4v2c-3.314 0-6-2.686-6-6 0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6zm25.464-1.95l8.486 8.486-1.414 1.414-8.486-8.486 1.414-1.414z' /%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
    }
    .bg-bank-note{
        background-image: url("data:image/svg+xml,%3Csvg width='100' height='20' viewBox='0 0 100 20' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M21.184 20c.357-.13.72-.264 1.088-.402l1.768-.661C33.64 15.347 39.647 14 50 14c10.271 0 15.362 1.222 24.629 4.928.955.383 1.869.74 2.75 1.072h6.225c-2.51-.73-5.139-1.691-8.233-2.928C65.888 13.278 60.562 12 50 12c-10.626 0-16.855 1.397-26.66 5.063l-1.767.662c-2.475.923-4.66 1.674-6.724 2.275h6.335zm0-20C13.258 2.892 8.077 4 0 4V2c5.744 0 9.951-.574 14.85-2h6.334zM77.38 0C85.239 2.966 90.502 4 100 4V2c-6.842 0-11.386-.542-16.396-2h-6.225zM0 14c8.44 0 13.718-1.21 22.272-4.402l1.768-.661C33.64 5.347 39.647 4 50 4c10.271 0 15.362 1.222 24.629 4.928C84.112 12.722 89.438 14 100 14v-2c-10.271 0-15.362-1.222-24.629-4.928C65.888 3.278 60.562 2 50 2 39.374 2 33.145 3.397 23.34 7.063l-1.767.662C13.223 10.84 8.163 12 0 12v2z' fill='%23312e81' fill-opacity='1' fill-rule='evenodd'/%3E%3C/svg%3E");
    }
</style>

<div class="my-10">
    <div class="flex-wrap flex justify-between items-baseline mb-7">
        <div class="text-3xl leading-9 font-bold mr-1">
            Shop by category
        </div>
        <a
            href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
            class="block text-lg leading-7 font-semibold text-blue-700"
        >
            Browse all →
        </a>
    </div>

    <div class="grid gap-4 grid-cols-2">
        <a
            href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
            class="shadow-lg rounded-md overflow-hidden flex items-center justify-center h-40 bg-pink-500 bg-wiggle col-span-2"
        >
            <div class="drop-shadow-lg text-white text-xl leading-10 font-bold uppercase sm:text-2xl md:text-3xl lg:text-4xl">
                New arrivals
            </div>
        </a>

        <a
            href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
            class="shadow-lg rounded-md overflow-hidden flex items-center justify-center h-72 bg-blue-800 bg-bank-note md:h-80"
        >
            <div class="drop-shadow-lg text-white text-xl leading-10 font-bold uppercase sm:text-2xl md:text-3xl lg:text-4xl">
                Women
            </div>
        </a>

        <a
            href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
            class="shadow-lg rounded-md overflow-hidden flex items-center justify-center h-72 bg-blue-800 bg-bank-note md:h-80"
        >
            <div class="drop-shadow-lg text-white text-xl leading-10 font-bold uppercase sm:text-2xl md:text-3xl lg:text-4xl">
                Men
            </div>
        </a>

        <a
            href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
            class="shadow-lg rounded-md overflow-hidden flex items-center justify-center h-72 bg-blue-800 bg-bank-note md:h-80"
        >
            <div class="drop-shadow-lg text-white text-xl leading-10 font-bold uppercase sm:text-2xl md:text-3xl lg:text-4xl">
                Gear
            </div>
        </a>

        <a
            href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
            class="shadow-lg rounded-md overflow-hidden flex items-center justify-center h-72 bg-blue-800 bg-bank-note md:h-80"
        >
            <div class="drop-shadow-lg text-white text-xl leading-10 font-bold uppercase sm:text-2xl md:text-3xl lg:text-4xl">
                Training
            </div>
        </a>
    </div>
</div>
