<!-- TrustBox widget - Slider -->
<div class="flex flex-col items-center bg-white">
<div class="trustpilot-widget w-full" data-locale="da-DK" data-template-id="54ad5defc6454f065c28af8b" data-businessunit-id="5701692e0000ff00058b00e1" data-style-height="240px" data-style-width="100%" data-theme="light" data-stars="1,2,3,4,5" data-review-languages="da">
  <a href="https://dk.trustpilot.com/review/murergrej.dk" target="_blank" rel="noopener">Trustpilot</a>
</div>
<button class=" mt-5 btn btn-secondary" onclick="window.open('https://dk.trustpilot.com/review/murergrej.dk', '_blank')">
  <?= __('View all reviews') ?></button>
</div>

<!-- End TrustBox widget -->
