<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * @category Scandiweb
 * @author   Scandiweb <info@scandiweb.com>
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Scandiweb\HyvaUi\Helper\Link as LinkHelper;
use Scandiweb\HyvaUi\Helper\Decode as DecodeHelper;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var LinkHelper */
$linkHelper = $this->helper(LinkHelper::class);
/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
$link_url_1 = $decodeHelper->decodeJSONHTMLEntity($block->getData('link_url_1'));
$link_url_2 = $decodeHelper->decodeJSONHTMLEntity($block->getData('link_url_2'));
$linkHref1 = $linkHelper->getLinkHref($block, $link_url_1);
$linkHref2 = $linkHelper->getLinkHref($block, $link_url_2);
?>
<div class="grid md:grid-cols-2 my-2 gap-4">
    <div class="relative h-[600px] sm:h-[500px] md:h-[400px]">
        <img class="absolute w-full h-full object-cover"
             alt="<?= $escaper->escapeHtml(__($block->getData('banner_image_1_alt'))) ?>"
             src="<?= $escaper->escapeHtmlAttr($block->getData('banner_image_1_src')) ?>"
             width="600"
             height="400"
             loading="lazy"
        />
        <div class="absolute bottom-0 w-full p-6 pt-28 bg-gradient-to-t to-transparent from-gray-800/75">
            <div class="mb-2 text-white text-6xl leading-none font-bold">
                <?= $escaper->escapeHtml(__($block->getData('banner_title_1'))) ?>
            </div>
            <a
            <?php if ($linkHref1): ?>
                href="<?= $escaper->escapeUrl($linkHref1) ?>"
                target="<?= $escaper->escapeHtmlAttr($linkHelper->getLinkTarget($link_url_1)); ?>"
            <?php endif; ?>
                class="block text-white text-2xl leading-8 font-semibold"
            >
                <?= $escaper->escapeHtml(__($block->getData('banner_subtitle_1'))) ?>
            </a>
        </div>
    </div>
    <div class="relative h-[600px] sm:h-[500px] md:h-[400px]">
        <img class="absolute w-full h-full object-cover"
             alt="<?= $escaper->escapeHtml(__($block->getData('banner_image_2_alt'))) ?>"
             src="<?= $escaper->escapeHtmlAttr($block->getData('banner_image_2_src')) ?>"
             width="600"
             height="400"
             loading="lazy"
        />
        <div class="absolute bottom-0 w-full p-6 pt-28 bg-gradient-to-t to-transparent from-gray-800/75">
            <div class="mb-2 text-white text-6xl leading-none font-bold">
                <?= $escaper->escapeHtml(__($block->getData('banner_title_2'))) ?>
            </div>
            <a
            <?php if ($linkHref2): ?>
                href="<?= $escaper->escapeUrl($linkHref2); ?>"
                target="<?= $escaper->escapeHtmlAttr($linkHelper->getLinkTarget($link_url_2)); ?>"
            <?php endif; ?>
                class="block text-white text-2xl leading-8 font-semibold"
            >
                <?= $escaper->escapeHtml(__($block->getData('banner_subtitle_2'))) ?>
            </a>
        </div>
    </div>
</div>
