<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/**
 * @category Scandiweb
 * @author   Scandiweb <info@scandiweb.com>
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Scandiweb\HyvaUi\Helper\Link as LinkHelper;
use Scandiweb\HyvaUi\Helper\Decode as DecodeHelper;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var LinkHelper */
$linkHelper = $this->helper(LinkHelper::class);
/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
$link_url_1 = $decodeHelper->decodeJSONHTMLEntity($block->getData('link_url_1'));
$link_url_2 = $decodeHelper->decodeJSONHTMLEntity($block->getData('link_url_2'));
$link_url_3 = $decodeHelper->decodeJSONHTMLEntity($block->getData('link_url_3'));
$link_url_4 = $decodeHelper->decodeJSONHTMLEntity($block->getData('link_url_4'));

/**
 * You can also get an image from `web/images/` in your theme:
 * $escaper->escapeHtmlAttr($block->getViewFileUrl('images/banner.jpg'))
 */
$banners = [
    [
        'image_url' => $block->getData('banner_image_1_src'),
        'image_alt' => __($block->getData('banner_image_1_alt')),
        'label' => __($block->getData('banner_title_1')),
        'url' => $linkHelper->getLinkHref($block, $link_url_1),
        'link_target' => $linkHelper->getLinkTarget($link_url_1)
    ],
    [
        'image_url' => $block->getData('banner_image_2_src'),
        'image_alt' => __($block->getData('banner_image_2_alt')),
        'label' => __($block->getData('banner_title_2')),
        'url' => $linkHelper->getLinkHref($block, $link_url_2),
        'link_target' => $linkHelper->getLinkTarget($link_url_2)
    ],
    [
        'image_url' => $block->getData('banner_image_3_src'),
        'image_alt' => __($block->getData('banner_image_3_alt')),
        'label' => __($block->getData('banner_title_3')),
        'url' => $linkHelper->getLinkHref($block, $link_url_3),
        'link_target' => $linkHelper->getLinkTarget($link_url_3)
    ],
    [
        'image_url' => $block->getData('banner_image_4_src'),
        'image_alt' => __($block->getData('banner_image_4_alt')),
        'label' => __($block->getData('banner_title_4')),
        'url' => $linkHelper->getLinkHref($block, $link_url_4),
        'link_target' => $linkHelper->getLinkTarget($link_url_4)
    ]
];
?>
<div class="grid grid-cols-2 md:grid-cols-4 my-2 gap-4">
    <?php foreach ($banners as $item): ?>
        <div class="relative h-80">
            <img class="absolute w-full h-full object-cover"
                alt="<?= $escaper->escapeHtml($item['image_alt']) ?>"
                src="<?= $escaper->escapeHtmlAttr($item['image_url']) ?>"
                width="340"
                height="610"
                loading="lazy"
            />
            <div class="absolute bottom-0 w-full p-7 pt-11 bg-gradient-to-t to-transparent from-gray-800/75">
                <a
                <?php if ($item['url']): ?>
                    href="<?= $escaper->escapeUrl($item['url']) ?>"
                    target="<?= $escaper->escapeHtmlAttr($item['link_target']); ?>"
                <?php endif; ?>
                    class="block text-white text-lg leading-7 font-bold text-center"
                >
                    <?= $escaper->escapeHtml($item['label']) ?>
                </a>
            </div>
        </div>
    <?php endforeach; ?>
</div>
