<?php

/**
 * @category    Murergrej
 * @package     Murergrej_Contact
 * @author      Beshoy Samuel <info@scandiweb.com>
 * @copyright   Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 */

declare(strict_types=1);

use Magento\Contact\Block\ContactForm;
use Magento\Contact\Helper\Data as ContactHelper;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\ReCaptcha;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var ContactForm $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha|null */

$formId = 'contact';
/** @var ContactHelper $contactHelper */
$contactHelper = $this->helper(ContactHelper::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that would break the dependency
// on the Magento_ReCaptchaContact module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<style>
    .pagebuilder-column-line figure > img {
        min-width: 100%;
    }
</style>
<div class="gap-4">
    <form class="form contact card"
          action="<?= $escaper->escapeUrl($block->getFormAction()) ?>"
          id="<?= $escaper->escapeHtmlAttr($formId) ?>"
          method="post"
          x-data="initContactForm()"
          @submit.prevent="submitForm()"
    >
        <fieldset class="p-6 md:pr-16">
            <div class="flex flex-col text-center w-full mb-4">
                <h2 class="sm:text-2xl text-xl font-bold title-font mb-4 text-gray-900 text-left">
                    <?= $escaper->escapeHtml(__('Write Us')) ?>
                </h2>
                <p class="w-full mx-auto leading-relaxed font-bold text-base text-left"><?= $escaper->escapeHtml(
                    __('Jot us a note and we’ll get back to you as quickly as possible.')
                ) ?></p>
            </div>
            <div class="flex flex-col">
                <div class="field name required py-2 text-left">
                    <label class="label text-gray-700" for="name">
                        <span class="text-base"><?= $escaper->escapeHtml(__('Name')) ?></span>
                    </label>
                    <input name="name" id="name" required title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                           value="<?= $escaper->escapeHtmlAttr(
                               $contactHelper->getPostValue('name')
                                   ?: $contactHelper->getUserName()
                           ) ?>"
                           class="form-input w-full md:w-4/5"
                           type="text"
                           placeholder="<?= $escaper->escapeHtml(__('Name')) ?>"
                    />
                </div>
                <div class="field email required py-2 text-left">
                    <label class="label text-gray-700" for="email">
                        <span class="text-base"><?= $escaper->escapeHtml(__('Email')) ?></span>
                    </label>
                    <input name="email" id="email" required title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           value="<?= $escaper->escapeHtmlAttr(
                               $contactHelper->getPostValue('email')
                                   ?: $contactHelper->getUserEmail()
                           ) ?>"
                           class="form-input w-full md:w-4/5"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           type="email"/>
                </div>
                <div class="field telephone py-2 text-left">
                    <label class="label text-gray-700" for="telephone">
                        <span class="text-base"><?= $escaper->escapeHtml(__('Phone Number')) ?></span>
                    </label>
                    <input name="telephone" id="telephone"
                           title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                           value="<?= $escaper->escapeHtmlAttr(
                               $contactHelper->getPostValue('telephone')
                           ) ?>"
                           class="form-input w-full md:w-4/5"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                           type="text"/>
                </div>
                <div class="field comment required py-2 w-full text-left">
                    <label class="label text-gray-700" for="comment">
                        <span class="text-base"><?= $escaper->escapeHtml(__('What’s on your mind?')) ?></span>
                    </label>
                    <textarea name="comment" id="comment" required
                              title="<?= $escaper->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                              class="form-input w-full md:w-4/5" cols="5" rows="3"><?= $escaper->escapeHtml(
                                  $contactHelper->getPostValue('comment')
                              ) ?></textarea>
                </div>
                <?= $block->getChildHtml('form.additional.info') ?>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
            </div>
        </fieldset>
        <div class="w-full pl-6 pb-6">
            <?= $block->getBlockHtml('formkey') ?>
            <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>" class="btn btn-primary">
                <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
        <div class="w-full">
            <?= $block->getChildHtml('form.additional.after') ?>
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
        </div>
    </form>
    <script>
        function initContactForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
    <div class="card">
        <?= $block->getChildHtml('contact.details') ?>
    </div>
</div>
