<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Address\Book;
use Magento\Framework\Escaper;

/** @var Book $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="block block-addresses-default my-6">
    <div class="block-title block-title text-2xl mb-6">
        <?= $escaper->escapeHtml(__('Default Addresses')) ?>
    </div>
    <div class="grid block-content lg:grid-cols-2 gap-4">
        <?php if ($customerDefaultBillingAddress = $block->getDefaultBilling()): ?>
            <div class="flex flex-col grow justify-between gap-3 box box-address-billing card p-4">
                <div>
                    <div class="text-gray-900 text-lg title-font font-medium">
                        <span class="font-bold"><?= $escaper->escapeHtml(__('Default Billing Address')) ?></span>
                    </div>
                    <div class="box-content">
                        <address>
                            <?= $block->getAddressHtml($block->getAddressById($customerDefaultBillingAddress)) ?>
                        </address>
                    </div>
                </div>
                <div class="box-actions btn btn-secondary mt-auto">
                    <a href="<?= $escaper->escapeUrl($block->getAddressEditUrl($customerDefaultBillingAddress)) ?>" class="flex gap-1">
                        <span><?= $escaper->escapeHtml(__('Change Billing Address')) ?></span>
                        <?= $heroicons->arrowRightHtml('', 16, 16); ?>
                    </a>
                </div>
            </div>
        <?php else: ?>
            <div class="flex flex-col grow justify-between gap-3 box box-billing-address card p-4">
                <div>
                    <div class="text-gray-900 text-lg title-font font-medium">
                        <span class="font-bold"><?= $escaper->escapeHtml(__('Default Billing Address')) ?></span>
                    </div>
                    <div class="box-content">
                        <p><?= $escaper->escapeHtml(__('You have no default billing address in your address book.')) ?></p>
                    </div>
                </div>
            </div>
        <?php endif ?>

        <?php if ($customerDefaultShippingAddress = $block->getDefaultShipping()): ?>
            <div class="flex flex-col grow justify-between gap-3 box box-address-shipping card p-4">
                <div>
                    <div class="text-gray-900 text-lg title-font font-medium">
                        <span class="font-bold"><?= $escaper->escapeHtml(__('Default Shipping Address')) ?></span>
                    </div>
                    <div class="box-content">
                        <address>
                            <?= $block->getAddressHtml($block->getAddressById($customerDefaultShippingAddress)) ?>
                        </address>
                    </div>
                </div>
                <div class="box-actions btn btn-secondary mt-auto">
                    <a href="<?= $escaper->escapeUrl($block->getAddressEditUrl($customerDefaultShippingAddress)) ?>" class="flex gap-1">
                        <span><?= $escaper->escapeHtml(__('Change Shipping Address')) ?></span>
                        <?= $heroicons->arrowRightHtml('', 16, 16); ?>
                    </a>
                </div>
            </div>
        <?php else: ?>
            <div class="flex flex-col grow justify-between gap-3 box box-shipping-address card p-4">
                <div>
                    <div class="text-gray-900 text-lg title-font font-medium">
                        <span class="font-bold"><?= $escaper->escapeHtml(__('Default Shipping Address')) ?></span>
                    </div>
                    <div class="box-content">
                        <p><?= $escaper->escapeHtml(__('You have no default shipping address in your address book.')) ?></p>
                    </div>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
