<?php /** @var \PWA\Import\Block\Adminhtml\Import $block */ ?>
<div class="page-columns import-container">
    <div class="error" id="import_error" style="display: none;"></div>
    <div class="admin__field field">
        <label for="import_action"><? __('Import Action') ?></label>
        <select id="import_action">
            <?php foreach ($block->getActions() as $action => $label): ?>
            <option value="<?= $action ?>"><?= $block->escapeHtml(__($label)) ?></option>
            <?php endforeach; ?>
        </select>
        <button id="import_execute" title="<?= __('Execute') ?>">
            <span><?= __('Execute') ?></span>
        </button>
    </div>
    <div class="admin__field field">
        <textarea id="import_log" rows="30" cols="200" readonly style="display: none"></textarea>
        <button id="load_last_log"><?= __('Load last log') ?></button>
    </div>
    <script type="text/javascript">
        var importConfig = <?= json_encode([
            'statusUrl' => $block->getUrl('*/*/status'),
            'logUrl' => $block->getUrl('*/*/log'),
            'startUrl' => $block->getUrl('*/*/start')
        ]) ?>;
        require(['jquery', 'prototype'], function ($) {
            var errorShown = false;
            var showError = function (text) {
                errorShown = true;
                $('#import_error').text(text).show();
            };
            var hideError = function () {
                if (errorShown) {
                    $('#import_error').hide();
                    errorShown = false;
                }
            }

            var inProgress = false;
            var starting = false;

            var startListening = function () {
                var offset = 0;
                var limit = 250;

                jQuery('#load_last_log').hide();
                jQuery('#import_log').val('').show();

                var update = function () {
                    new Ajax.Request(importConfig.logUrl, {
                        method: 'get',
                        loaderArea: false,
                        parameters: {
                            offset: offset,
                            limit: limit
                        },
                        /**
                         * @param {Object} response
                         */
                        onSuccess: (response) => {
                            var json = response.responseJSON || {};
                            if (json.code == 200) {
                                hideError();
                                var logEl = document.getElementById('import_log');
                                var regex = /(^stdout: |^stderr: |\u001b\[\d+m)/g;
                                json.result.lines.forEach(function (line) {
                                    logEl.value += line.replace(regex, '');
                                });
                                offset += json.result.lines.length;
                                if (json.result.total > offset) {
                                    setTimeout(update, 0);
                                } else if (json.result.running) {
                                    setTimeout(update, 500);
                                } else {
                                    inProgress = false;
                                    $('#import_execute').prop('disabled', false);
                                }
                            } else {
                                showError(json.result || json.message || 'An error has occured.');
                                inProgress = false;
                                $('#import_execute').prop('disabled', false);
                            }
                        },
                        onFailure: (response) => {
                            var json = response.responseJSON || {};
                            showError(json.result || json.message || 'Request failed.');
                            inProgress = false;
                            $('#import_execute').prop('disabled', false);
                        }
                    })
                }

                update();
            }

            $('#import_execute').click(function () {
                if (inProgress || starting) {
                    return;
                }
                starting = true;
                $('#import_execute').prop('disabled', true);
                new Ajax.Request(importConfig.startUrl, {
                    method: 'post',
                    parameters: {
                        command: $('#import_action').val()
                    },
                    /**
                     * @param {Object} response
                     */
                    onSuccess: (response) => {
                        starting = false;
                        var json = response.responseJSON || {};
                        if (json.code == 200 && json.result == 'OK') {
                            hideError();
                            inProgress = true;
                            startListening();
                        } else {
                            $('#import_execute').prop('disabled', false);
                            showError(json.result || json.message || 'An error has occured.');
                        }
                    },
                    onFailure: (response) => {
                        starting = false;
                        $('#import_execute').prop('disabled', false);
                        var json = response.responseJSON || {};
                        showError(json.result || json.message || 'Request failed.');
                    }
                })
            });

            $('#load_last_log').click(function () {
                inProgress = true;
                $('#import_execute').prop('disabled', true);
                startListening();
            })
        });
    </script>
</div>
<style>
    .error {
        background-color: lightcoral;
        padding: 5px;
        border-radius: 5px;
    }
    #import_log {
        width: 100%;
    }
</style>
