<?php
/**
 * @category    Scandiweb
 * @author      Aleksejs Prjahins <info@scandiweb.com>
 * @copyright   Copyright (c) 2023 Scandiweb, Inc (http://scandiweb.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<?= $block->getLayout()
    ->createBlock(Magento\Cms\Block\BlockByIdentifier::class)
    ->addData(['identifier' => 'hyva_ui_product_card'])
    ->toHtml();
?>

