<?php

/**
 * @category Scandiweb
 * @author   Scandiweb <info@scandiweb.com>
 */

declare(strict_types=1);

use Scandiweb\HyvaUi\Block\ScandiwebSlider;
use Scandiweb\HyvaUi\Helper\Decode as DecodeHelper;

/** @var ScandiwebSlider $block */

/** @var DecodeHelper $decodeHelper */
$decodeHelper = $this->helper(DecodeHelper::class);
$cards = $block->getData('cards');
$slides = $decodeHelper->decodeJSONHTMLEntity($cards);
?>

<h3>
    <?= $escaper->escapeHtml($block->getData('block_title')); ?>
</h3>
<div>
    <?= $escaper->escapeHtml($block->getData('block_subtitle')); ?>
</div>
<?php if ($slides): ?>
    <div class="glider-contain w-full" x-data x-init="initCarousel($el);">
        <div class="m-0 pt-10 flex flex-row flex-wrap w-full gap-4 flex-grow lg:flex-row" data-role="glider-content">
            <?php foreach ($slides as $slide): ?>                    
                <a href="<?= $escaper->escapeUrl($slide['slide_img_url']) ?>" class="overflow-hidden relative home-category-slide !left-0 slide basis-1 rounded flex-grow flex flex-col justify-between min-h-[320px] md:min-h-[400px] min-w-[232px] md:min-w-[288px] 2xl:min-w-[300px] 2xl:max-w-[400px]">
                    <div class="min-h-full bg-cover lazyload"
                        data-background-image="linear-gradient(to top, rgb(30 41 59), rgba(255,255,255, 0), rgba(255,255,255, 0)), url(<?= $escaper->escapeHtmlAttr($slide['slide_img_src'][0]['url']); ?>)">
                        <?php if ($slide['slide_img_label']): ?>
                            <div
                                class="bg-black p-[10px] text-sm-ui text-white inline rounded-lg absolute translate-y-2 translate-x-2 transform">
                                <?= $escaper->escapeHtml($slide['slide_img_label']); ?>
                            </div>
                        <?php endif; ?>
                        <div class="m-4 mt-0 absolute bottom-0 bg-black p-3">
                            <?php if ($slide['slide_img_title']): ?>
                                <div class="text-lg font-semibold break-all text-white mb-2">
                                    <?= $escaper->escapeHtml($slide['slide_img_title']); ?>
                                </div>
                            <?php endif; ?>

                            <?php if ($slide['slide_img_subtitle']): ?>
                                <div class="break-word text-base text-white">
                                    <?= $escaper->escapeHtml($slide['slide_img_subtitle']); ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </a>
            <?php endforeach; ?>
        </div>
        <div class="absolute mb-2 cursor-pointer flex-row right-8 top-[6px] hidden md:flex">
            <div
                class="glider-prev border rounded-full mr-4 w-[32px] h-[32px] border-solid border-black flex items-center justify-center glider-btn glider-btn-prev-hover disabled">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                </svg>
            </div>
            <div
                class="glider-next border rounded-full w-[32px] h-[32px] border-solid border-black flex items-center justify-center glider-btn glider-btn-next-hover">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                </svg>
            </div>
        </div>
    </div>
<?php endif; ?>
