<div class="bg-gray-50 leading-6 text-gray-500 flex flex-col lg:flex-row">

    <div class="relative lg:flex-1">
        <img
             alt="Man holding bike while standing on gray mountain"
             class="lg:w-full lg:h-full lg:object-cover"
             src="https://unsplash.com/photos/ByUAo3RpA6c/download?force=true&auto=format&fit=crop&w=720&q=80"
             width="720"
             height="949"
             loading="lazy"
        />
        <div class="bg-gradient-to-t from-blue-800/50 pt-48 absolute bottom-0 px-6 py-8 left-0 w-full lg:hidden">
            <span class="mb-2 inline-block uppercase bg-blue-600 rounded px-2 py-1 text-blue-100 text-lg leading-7
                         font-semibold lg:text-xl"
            >
                About us
            </span>

            <h1 class="text-4xl leading-10 font-bold text-white lg:text-5xl">
                Everything you need to know
            </h1>
        </div>
    </div>


    <div class="p-6 flex flex-col gap-8 lg:flex-row lg:flex-wrap lg:flex-1">
        <div class="flex flex-col gap-8 lg:w-full">

            <div class="hidden lg:block">
                <span class="mb-2 inline-block uppercase bg-blue-100 rounded px-2 py-1 text-blue-600 text-lg leading-7
                             font-semibold lg:text-xl"
                >
                    About us
                </span>

                <h1 class="text-4xl leading-10 font-bold text-gray-800 lg:text-5xl">
                    Everything you need to know
                </h1>
            </div>

            <p class="text-lg leading-7 font-medium">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eu neque aliquam metus porta
                sagittis. Nunc velit ligula, vestibulum et neque et, ullamcorper convallis lacus. Donec a neque iaculis,
                dictum nisl ut, dictum nisi. Praesent sagittis augue ac pulvinar lobortis. Quisque molestie velit metus,
                eu ultricies ligula accumsan tempus.
            </p>
            <p>
                Aliquam non enim in nulla pellentesque rhoncus. Aenean faucibus ligula quam, eu iaculis erat rhoncus
                vel. Maecenas non est et nisi accumsan faucibus vitae sit amet sapien. Maecenas euismod, urna vitae
                elementum congue, nulla diam semper odio, ac vehicula nisl quam eu nibh. Quisque lacinia orci mi, ac
                auctor mi mattis vel. Mauris aliquet nisi a pulvinar varius. Curabitur luctus dolor ac nibh rutrum
                lacinia. Curabitur vestibulum commodo lectus eget dictum. Etiam at sagittis lacus. Pellentesque mattis
                leo non odio vestibulum ultrices. Duis at tellus tellus.
            </p>
            <div class="flex gap-3">
                <div class="text-8xl leading-10 font-bold text-blue-100">
                    “
                </div>
                <div class="text-2xl leading-8 font-light text-gray-700">
                    Nullam nec tortor semper, mattis tortor ut, dictum augue. Etiam vitae tellus turpis. Aenean dictum
                    metus non turpis luctus, ut egestas mi facilisis.
                </div>
            </div>
            <p>
                Morbi in lectus at eros luctus mollis. Vivamus lobortis urna in quam dignissim tempus. Sed volutpat
                ipsum vitae justo sagittis venenatis. Vestibulum eros elit, scelerisque eget velit a, viverra eleifend
                augue. Integer in ante non felis ornare tempus. Nam ut mi id lorem maximus ornare sit amet vitae enim.
            </p>
            <p>
                Praesent sed porta risus. Etiam eget arcu venenatis, feugiat magna sit amet, auctor sapien. Maecenas
                sed nulla dui. Cras egestas tortor felis, a porta risus consectetur in. Curabitur sed nunc mauris.
                Pellentesque vulputate scelerisque dolor eget semper. Aliquam hendrerit nibh sit amet eros sagittis
                molestie.
            </p>

        </div>
    </div>
</div>
