<!-- TrustBox widget - Slider -->
<div class="flex justify-center items-center bg-white pb-14 lg:pb-[72px]">
  <div class="trustpilot-widget md:w-4/5" data-locale="en-US" data-template-id="54ad5defc6454f065c28af8b"
      data-businessunit-id="5701692e0000ff00058b00e1" data-style-height="240px" data-style-width="100%" data-stars="1,2,3,4,5" data-review-languages="en">
    <a href="https://www.trustpilot.com/review/murergrej.dk" target="_blank" rel="noopener">Trustpilot</a>
  </div>
</div>
