<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer\ForgotPasswordButton;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Customer\Block\Account\Forgotpassword;
use Magento\Framework\Escaper;

/** @var Forgotpassword $block */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha */
/** @var ForgotPasswordButton $forgotPasswordButtonViewModel */
/** @var ViewModelRegistry $viewModels */

$forgotPasswordButtonViewModel = $viewModels->require(ForgotPasswordButton::class);
$storeConfig = $viewModels->require(StoreConfig::class);
$isAutocompleteEnabled = $storeConfig->getStoreConfig('customer/password/autocomplete_on_storefront');

$formId = 'user_forgotpassword';

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaCustomer module
$recaptcha = $block->getData('viewModelRecaptcha');
?>

<div class="w-full bg-white">
    <form action="<?= $escaper->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
            method="post"
            id="<?= $escaper->escapeHtmlAttr($formId) ?>"
            x-data="initPasswordForm()"
            @submit.prevent="submitForm();"
            class="w-full md:w-2/3 lg:w-1/2">
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="formId" value="<?= $escaper->escapeHtmlAttr($formId) ?>"/>
        <?= $block->getChildHtml('form_fields_before') ?>
        <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
        <div class="fieldset flex flex-col gap-y-2">
            <div>
                <span class="text-secondary font-bold">
                    <?= $escaper->escapeHtml(
                    __('Please enter your email address below to receive a password reset link.')
                ) ?>
                </span>
            </div>
            <div class="field email required">
                <label for="email_address" class="label">
                    <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                </label>
                <div class="control">
                    <input type="email"
                           name="email"
                           alt="email"
                           id="email_address"
                           class="form-input w-full"
                           autocomplete="<?= $isAutocompleteEnabled ? 'username' : 'off' ?>"
                           required
                           value="<?= $escaper->escapeHtmlAttr($block->getEmailValue()) ?>">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>
        </div>
        <div class="flex flex-col gap-2 lg:flex-row justify-between">
            <button type="submit" class="lg:order-2  action submit btn btn-primary"
                <?php if ($forgotPasswordButtonViewModel->disabled()): ?> data-recaptcha-btn<?php endif; ?>
            >
                <span><?= $escaper->escapeHtml(__('Reset My Password')) ?></span>
            </button>
            <a class="lg:order-1 action btn btn-secondary"
                href="<?= $escaper->escapeUrl($block->getLoginUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </form>
    <script>
        function initPasswordForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_CUSTOMER_FORGOT_PASSWORD) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>

