<?php
/**
 * @category    Scandiweb
 * @author      Aleksejs Prjahins <info@scandiweb.com>
 * @copyright   Copyright (c) 2023 Scandiweb, Inc (http://scandiweb.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="w-full">
    <div class="w-full lg:w-1/4 float-left lg:float-right lg:order-2 top-0 lg:sticky">
        <div class="flex pb-3 my-2 border-b-2 border-gray-300 flex-col">
            <h2 class="w-full text-2xl text-center text-gray-900 title-font font-base md:text-left">
                <?= $escaper->escapeHtml(__('Summary')) ?>
            </h2>
        </div>
        <?= $block->getChildHtml('freeshipping_progressbar.cart') ?>
        <?= $block->getChildHtml('cart.summary') ?>
    </div>
    <div class="w-full lg:w-3/4 float-left lg:order-1 lg:pr-8">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
    </div>
    <div class="w-full lg:w-3/4 lg:pr-8">
        <?= $block->getChildHtml('cart.discount') ?>
    </div>
</div>
