<?php /** @var \Murergrej\Customer\Block\Account\ForgotPassword $block */ ?>
<div id="forgot-password-container" style="display: none;">
    <a href="<?= $block->getLink() ?>" onclick="event.preventDefault(); document.getElementById('forgot-password-form').submit();"><?= __('Forgot Your Password?') ?></a>
</div>
<script type="text/javascript">
    requirejs(['jquery'], function ($) {
        var element = $('#forgot-password-container').detach();
        $('.fieldset.password').append(element);
        element.show();
    });
</script>
