<?php
/**
 * @category    Murergrej
 * @package     Hairtalk_Hyva
 * @author      Ernests Verins <info@scandiweb.com>
 * @copyright   Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 */

declare(strict_types=1);

// phpcs:disable Magento2.Files.LineLength.MaxExceeded

use Magento\Catalog\Pricing\Price\FinalPrice;
use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\ProductPrice;
use Magento\Catalog\Pricing\Price\RegularPrice;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaIcons */
$hyvaIcons = $viewModels->require(SvgIcons::class);

/** @var Renderer $block */
/** @var Escaper $escaper */

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
$productViewModel = $viewModels->require(ProductPage::class);
$productPriceViewModel = $viewModels->require(ProductPrice::class);
$regularPrice = $productPriceViewModel->getPriceValue(RegularPrice::PRICE_CODE, $product);
$quoteItemQty = $item->getQty();
$finalPrice = $productPriceViewModel->getPriceValueExclTax(FinalPrice::PRICE_CODE, $product);
$quotItemTotal = floatval($item->getRowTotalInclTax());
$productPrice = (floatval($item->getPriceInclTax()) * $quoteItemQty);
?>
<tbody
  id="cart-item-<?= $item->getId() ?>"
  class="cart item bg-secondary-lighter border-2 border-white"
>
    <tr class="item-info align-top text-left lg:text-right flex flex-wrap lg:table-row lg:flex-nowrap lg:pb-1.5 lg:pb-0">
        <td
          data-th="<?= $escaper->escapeHtml(__('Item')) ?>"
          class="col item flex flex-wrap text-left w-full lg:flex-nowrap lg:w-auto lg:w-4/6 lg:w-[35%] lg:w-full order-1"
        >
            <?php if ($block->hasProductUrl()): ?>
            <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
               title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo shrink-0 px-px py-px max-w-24 lg:max-w-none">
                <?php else: ?>
                <span class="product-item-photo shrink-0">
                <?php endif;?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')
                    ->setTemplate('Magento_Catalog::product/image.phtml')
                    ->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
            </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details grow pt-1.5 pr-4 pl-3 pb-0 text-sm
                lg:text-base lg:pr-0 lg:pl-6 lg:pb-4 lg:pt-4">
                <strong class="product-item-name break-words">
                    <?php if ($block->hasProductUrl()): ?>
                        <a
                          href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                          class="no-underline text-primary block mb-1 overflow-hidden max-w-[194px] lg:max-w-none"
                          style="display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;"
                        >
                            <?= $escaper->escapeHtml($block->getProductName()) ?>
                        </a>
                    <?php else: ?>
                        <?= $escaper->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <div class="text-xs">
                    <span class="text-primary-lighter"><?= $escaper->escapeHtml(__('SKU')) ?>: </span>
                    <span class="font-extrabold text-primary-lighter">
                        <?= $escaper->escapeUrl($block->getProduct()->getSku()) ?>
                    </span>
                </div>
                <?php if ($options = $block->getOptionList()): ?>
                    <dl class="item-options w-full break-all mt-1.5 text-xs clearfix">
                        <?php foreach ($options as $option): ?>
                            <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                            <dt class="text-primary-lighter float-left clear-left mr-1">
                                <?= $escaper->escapeHtml($option['label']) ?>:
                            </dt>
                            <dd class="float-left font-extrabold text-primary-lighter">
                                <?php if (isset($formatedOptionValue['full_view'])): ?>
                                    <?= $escaper->escapeHtml($formatedOptionValue['full_view']) ?>
                                <?php else: ?>
                                    <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <div class="justify-start hidden gap-4 flex lg:flex lg:pt-4">
                    <?= /* @noEscape */ $block->getActions($item) ?>
                </div>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class= "cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $escaper->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>
        <td class="col flex qty pt-3 pb-4 lg:pt-2 px-4 block w-full lg:w-1/3 lg:w-auto lg:table-cell order-3 ">
            <div class="justify-start gap-4 lg:hidden flex lg:flex lg:pt-4 max-lg:flex-1">
                <?= /* @noEscape */ $block->getActions($item) ?>
            </div>
            <div
                class="product-cart-quantity flex items-center"
                x-data="{ qty: <?= $item->getQty() ?> }"
                @private-content-loaded.window="
                   qty = ($event.detail.data.cart.items.find(item => item.item_id == <?= $item->getId() ?>) || {}).qty || 0;
                "
            >
                <div class="product-qty-wrapper grid items-center w-[80px] h-[52px] bg-white border-2">
                    <label for="qty[<?= (int)$product->getId() ?>]" class="sr-only">
                        <?= $escaper->escapeHtml(__('Qty')) ?>
                    </label>
                    <input
                        id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty"
                        name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]"
                        value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                        type="number"
                        size="4"
                        step=1
                        title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                        class="form-input pl-4 py-2.5 pr-2 text-center w-full font-semibold border-0
                         invalid:ring-2 invalid:ring-red-500"
                        required
                        min="1"
                        data-role="cart-item-qty"
                        x-model="qty"
                        @input="updateQuantity(<?= $item->getId() ?>, qty)"
                    />
                    <div class="product-qty-buttons flex flex-col justify-between">
                        <button
                            type="button"
                            class="up"
                            @click="qty = Math.max(1, parseInt(qty) + 1); updateQuantity(<?= $item->getId() ?>, qty)"
                        >
                            <?= $hyvaIcons->renderHtml('up', '', 12, 12) ?>
                        </button>
                        <button
                            type="button"
                            class="down"
                            @click="qty = Math.max(1, parseInt(qty) - 1); updateQuantity(<?= $item->getId() ?>, qty)"
                        >
                            <?= $hyvaIcons->renderHtml('down', '', 12, 12) ?>
                        </button>
                    </div>
                </div>
            </div>
        </td>
        <td class="col subtotal px-4 pb-1.5 block w-full text-right lg:w-1/3 lg:w-auto lg:table-cell lg:pt-6
            lg:pl-0 lg:pr-6 lg:pb-0 order-2">
            <?php
            $quantity = $item->getQty();
            $productPriceHtml = $block->getProductPriceHtml($product);
            $specialPriceExclTax = 0;
            $specialPriceInclTax = 0;
            $regularPriceInclTax = 0;

            if (strpos($productPriceHtml, 'old-price') !== false) {
                if (
                  (float)$product->getSpecialPrice() > (float)$item->getPrice() ||
                  (float)$product->getPrice() > (float)$item->getPrice()
                ) {
                    $specialPriceExclTax = (float)$item->getBaseRowTotal();
                    $specialPriceInclTax = (float)$item->getRowTotalInclTax();

                } else {
                    preg_match('/data-price-amount="([\d\.]+)"\s+data-price-type="basePrice"/', $productPriceHtml, $matches);
                    $specialPriceExclTax = isset($matches[1]) ? floatval(str_replace(',', '', $matches[1])) * $quantity : 0;

                    preg_match('/data-price-amount="([\d\.]+)"\s+data-price-type="finalPrice"/', $productPriceHtml, $matches);
                    $specialPriceInclTax = isset($matches[1]) ? floatval(str_replace(',', '', $matches[1])) * $quantity : 0;
                }

                // Extract Regular Price Including Tax (from old price)
                preg_match('/data-price-amount="([\d\.]+)"\s+data-price-type="oldPrice"/', $productPriceHtml, $matches);
                $regularPriceInclTax = isset($matches[1]) ? floatval(str_replace(',', '', $matches[1])) * $quantity : 0;
            } else {
                if (
                    (float)$product->getSpecialPrice() > (float)$item->getPrice() ||
                    (float)$product->getPrice() > (float)$item->getPrice()
                ) {
                    $specialPriceExclTax = (float)$item->getBaseRowTotal();
                    $specialPriceInclTax = (float)$item->getRowTotalInclTax();
                } else {
                    // Extract Regular Price Excluding Tax
                    preg_match('/data-price-amount="([\d\.]+)"\s+data-price-type="basePrice"/', $productPriceHtml, $matches);
                    $specialPriceExclTax = isset($matches[1]) ? floatval(str_replace(',', '', $matches[1])) * $quantity : 0;

                    preg_match('/data-price-amount="([\d\.]+)"\s+data-price-type="finalPrice"/', $productPriceHtml, $matches);
                    $specialPriceInclTax = isset($matches[1]) ? floatval(str_replace(',', '', $matches[1])) * $quantity : 0;
                }
            }

            $formattedTotalSpecialPriceExclTax = $block->convertPrice($specialPriceExclTax, true);
            $formattedTotalSpecialPriceInclTax = $block->convertPrice($specialPriceInclTax, true);
            $regularPriceExclTax = $regularPriceInclTax ?
                $block->convertPriceInclToExclTax($regularPriceInclTax, $product) : 0;
            $formattedRegularPriceExclTax = $regularPriceExclTax ? $block->convertPrice($regularPriceExclTax, true) : '';
            $formattedRegularPriceInclTax = $regularPriceInclTax ? $block->convertPrice($regularPriceInclTax, true) : '';
            $formattedRegularPriceExclTaxTierPrice = $block->convertPrice(($finalPrice * $quoteItemQty), true);
            $formattedRegularPriceInclTaxTierPrice = $block->convertPrice($regularPrice * $quoteItemQty, true);
            ?>
            <div>
                <div
                  @private-content-loaded.window="
                    item = $event.detail.data.cart.items.find(item => item.item_id == <?= $item->getId() ?>) ||
                     { qty: 0, price_inc_tax_full: 0, row_total: 0, base_final_price: 0, row_total_incl_tax: 0 };
                  "
                >
                    <div class="flex flex-col text-right items-end">
                        <div class="flex">
                            <p x-show="vatMode == 'excluding' && isDataStable(item) &&
                             (parseFloat(item.row_total) < parseFloat(item.qty * item.base_final_price))"
                            >
                                <span
                                  class="font-extrabold text-sm text-secondary line-through mr-1"
                                  x-html="hyva.formatPrice(item.qty * item.base_final_price)"
                                ></span>
                            </p>
                            <p>
                                <span
                                  class="font-extrabold"
                                  :class="{
                                  'included-tax-price text-base': vatMode == 'excluding',
                                  'text-sm': vatMode != 'excluding',
                                  'text-red': vatMode == 'excluding' && isDataStable(item) &&
                                   (parseFloat(item.row_total) < parseFloat(item.qty * item.base_final_price))
                                  }"
                                  x-html="hyva.formatPrice(item.row_total)"
                                ></span>
                                <span class="text-primary-lighter text-xs font-bold">
                                    <?= $escaper->escapeHtml(__('Excl. Tax')) ?>
                                </span>
                            </p>
                        </div>
                        <div class="flex">
                            <p x-show="vatMode == 'including' && isDataStable(item) &&
                             (parseFloat(item.row_total) < parseFloat(item.qty * item.base_final_price))"
                            >
                                <span
                                  class="font-extrabold text-sm text-secondary line-through mr-1"
                                  x-html="hyva.formatPrice(item.qty * item.price_inc_tax_full)"
                                ></span>
                            </p>
                            <p>
                                <span
                                  class="font-extrabold"
                                  :class="{
                                  'included-tax-price text-base': vatMode == 'including',
                                  'text-sm': vatMode != 'including',
                                  'text-red': vatMode == 'including' && isDataStable(item) &&
                                   (parseFloat(item.row_total) < parseFloat(item.qty * item.base_final_price))
                                  }"
                                  x-html="hyva.formatPrice(item.row_total_incl_tax)"
                                ></span>
                                <span class="text-primary-lighter text-xs font-bold">
                                    <?= $escaper->escapeHtml(__('Incl. Tax')) ?>
                                </span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
</tbody>
