<?php
 /**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */
?>
<template x-if="segment.code === 'tax'">
    <div class="tax_cart flex lg:pb-4 lg:px-6 px-4 bg-cream text-sm lg:grid lg:grid-cols-2 lg:w-full border-container">
        <div class="w-7/12 text-left lg:w-auto max-lg:border-b-2"
             x-html="segment.title"
        ></div>
        <div class="w-5/12 font-extrabold text-right lg:w-auto max-lg:border-b-2 max-lg:pb-3"
             x-text="hyva.formatPrice(segment.value)"
        ></div>
    </div>
</template>
