<!-- TrustBox widget - Slider -->
 <div class="flex flex-col items-center ">
<div class="trustpilot-widget w-full" data-locale="da-DK" data-template-id="54ad5defc6454f065c28af8b" data-businessunit-id="5701692e0000ff00058b00e1" data-style-height="240px" data-style-width="100%" data-theme="light" data-stars="1,2,3,4,5" data-review-languages="da">
  <a href="https://dk.trustpilot.com/review/murergrej.dk" target="_blank" rel="noopener">Trustpilot</a>
</div>
<button class="flex items-center w-[91%] max-md:mx-4 max-md:mt-8 h-14 md:w-auto justify-center font-extrabold font-[16px] px-6 py-4 0 border-primary border-2 border-primary-lighter" onclick="window.open('https://dk.trustpilot.com/review/murergrej.dk', '_blank')">
  VIEW ALL REVIEWS</button>
</div>

<!-- End TrustBox widget -->
