<?php
/**
 * @category Murergrej
 * @package  Murergrej_Category
 * @author   Ahmed Elbltagy <info@scandiweb.com>
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 */
?>
<?php
use Hyva\Theme\ViewModel\SvgIcons;
/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
$categories = $block->getChildCategories();
if (!empty($categories)):
    $uniqueId = uniqid('__');
    $title = $block->getData('widget_title') ?: 'Brand Images';
    $swiperUrl = $block->getViewFileUrl('Murergrej_CmsBlocks::js/swiper.min.js');
    $swiperCssUrl = $block->getViewFileUrl('Murergrej_CmsBlocks::css/swiper.min.css');
?>
<section
    class="flex flex-col w-full"
    x-data="initSliderComponent_2('<?= $uniqueId; ?>', '<?= $swiperUrl; ?>', '<?= $swiperCssUrl; ?>')"
    x-init="init();"
    x-id="['slider-nav', 'slider-desc', 'slider-id']"
    role="group"
    aria-roledescription="<?= $escaper->escapeHtmlAttr(__('Carousel')) ?>"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Carousel %1', $title)) ?>"
    :aria-describedby="$id('slider-desc')"
>
    <div class="relative xl:ml-0 bg-white md:pb-12 pb-8 pt-4 md:pt-6">
        <div class="flex items-center relative justify-between">  <!-- Flex container for buttons and slider -->
        <div class="flex-shrink-0 ml-10 mr-4 hidden xl:block" >
                <button type="button" aria-label="<?= $escaper->escapeHtmlAttr(__('Previous slide')) ?>"
                        class="swiper-prev_<?= $uniqueId ?> border-2 p-3.5 bg-white flex items-center justify-center w-[52px] h-[52px]">
                    <?= $hyvaicons->renderHtml('next', 'rotate-180', 24, 24) ?>
                </button>
            </div>
            <div class=" swiper swiper_<?= $uniqueId ?> overflow-hidden flex-grow bg-white !pr-4 !pl-4 md:pr-0 relative">
                <div class="swiper-wrapper flex !h-auto">
                    <?php foreach ($categories as $category):
                        // Generate a unique ID for each slide
                        $slideUniqueId = $uniqueId . '-' . uniqid();
                    ?>
                        <div class="swiper-slide flex items-center justify-center" id="slide-<?= $slideUniqueId; ?>">
                            <a class="flex md:h-[196px] h-30 no-underline " href="<?= $category['url']; ?>">
                                <div class="flex flex-col w-full items-center justify-center category_slider
                                 hover:bg-primary border-2 border-cream bg-cream hover:border-blue hover:text-white">
                                    <div class=" flex w-full items-center justify-center bg-white md:min-h-36 min-h-20">
                                    <?php if ($category['brand_image']): ?>
                                        <img
                                            class="flex justify-items-center w-auto md:py-4 py-2 md:h-36 h-20"
                                            src="<?=$category['brand_image']; ?>"
                                            alt="<?= $escaper->escapeHtml($category['name']); ?>"
                                        />
                                    <?php endif; ?>
                                    </div>
                                    <div class="w-4/5 md:h-[52px] h-10 items-center justify-center flex">
                                        <p class="text-base leading-[18px] font-extrabold uppercase
                                            text_category_slider truncate md:leading-5">
                                            <?= $escaper->escapeHtml($category['name']);?>
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="swiper-scrollbar md:!w-[94%] swiper-scrollbar_<?= $uniqueId ?>"></div>
            </div>
            <div class="absolute mr-10 ml-4 hidden xl:block top-1/2 right-0 z-10 translate-y-[-80%]">
                <button type="button" aria-label="<?= $escaper->escapeHtmlAttr(__('Next slide')) ?>"
                        class="swiper-next_<?= $uniqueId ?> border-2 p-3.5 bg-white flex items-center justify-center w-[52px] h-[52px]">
                    <?= $hyvaicons->renderHtml('next', '', 24, 24) ?>
                </button>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>

<!-- Include Swiper Initialization Script with Custom Configuration -->
<script>
function initSliderComponent_2(uniqueId, swiperJsUrl, swiperCssUrl) {
    return {
        init() {
            if (!window.Swiper) {
                this.addJsScript(swiperJsUrl);
                this.addCss(swiperCssUrl);
            } else {
                this.initializeSwiper(uniqueId);
            }
        },
        initializeSwiper(uniqueId) {
            const swiperElement = this.$el.querySelector('.swiper_' + uniqueId);

            if (!swiperElement) {
                return;
            }

            const swiper = new Swiper(swiperElement, {
                slidesPerView: '2.5',
                spaceBetween: 12,
                draggable: true,
                touchEventsTarget: 'container',
                navigation: {
                    nextEl: '.swiper-next_' + uniqueId,
                    prevEl: '.swiper-prev_' + uniqueId,
                },
                scrollbar: {
                    el: '.swiper-scrollbar_' + uniqueId,
                    draggable: true,
                },
                breakpoints: {
                    768: {
                        spaceBetween: 16,
                        slidesPerView: 3.25,
                    },
                    1440: {
                        spaceBetween: 16,
                        slidesPerView: 6, // Adjusted for this specific slider
                    },
                }
            });
        },
        addJsScript(swiperJsUrl) {
            const script = document.createElement('script');
            script.type = 'text/javascript';
            script.addEventListener('load', () => {
                this.initializeSwiper(uniqueId);
            });
            script.src = swiperJsUrl;
            document.head.appendChild(script);
        },
        addCss(swiperCssUrl) {
            const link = document.createElement('link');
            link.type = 'text/css';
            link.rel = 'stylesheet';
            link.href = swiperCssUrl;
            document.head.appendChild(link);
        },
    }
}
</script>
