<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Account\Dashboard\Address;
use Magento\Framework\Escaper;

/** @var Address $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="block block-dashboard-addresses mb-5">
    <h2 class="block-title my-6 flex justify-between items-center card px-4 py-5 max-lg:flex-col max-lg:items-start">
        <span class="text-2xl block"><?= $escaper->escapeHtml(__('Address Book')) ?></span>
        <a class="btn btn-primary action edit inline-block max-lg:w-full max-lg:text-center max-lg:mt-3"
           href="<?= $escaper->escapeUrl($block->getAddressBookUrl()) ?>"
        >
            <span><?= $escaper->escapeHtml(__('Manage Addresses')) ?></span>
        </a>
    </h2>
    <div class="block-content">
        <div class="flex flex-wrap justify-between -m-4">
            <div class="lg:w-1/2 w-full p-4">
                <div class="flex px-4 py-5 gap-2 sm:flex-row flex-col h-full card">
                    <div class="flex grow flex-col gap-y-2">
                        <p class="font-bold title-fon">
                            <span><?= $escaper->escapeHtml(__('Default Billing Address')) ?></span>
                        </p>
                        <address>
                            <?= $block->getPrimaryBillingAddressHtml() ?>
                        </address>
                        <a
                            class="btn btn-primary w-full inline-flex items-center md:text-sm mt-auto"
                            href="<?= $escaper->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>"
                            data-ui-id="default-billing-edit-link"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Edit Address - billing default')) ?>"
                        >
                            <span><?= $escaper->escapeHtml(__('Edit Address')) ?></span>
                            <?= $heroicons->arrowRightHtml('ml-2', 16, 16, ['aria-hidden' => 'true']); ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="lg:w-1/2 w-full p-4">
                <div class="flex flex px-4 py-5 gap-2 sm:flex-row flex-col h-full card">
                    <div class="flex grow flex-col gap-y-2">
                        <p class="font-bold title-fon">
                            <span><?= $escaper->escapeHtml(__('Default Shipping Address')) ?></span>
                        </p>
                        <address>
                            <?= $block->getPrimaryShippingAddressHtml() ?>
                        </address>
                        <a
                            class="btn btn-primary w-full inline-flex items-center md:text-sm mt-auto"
                            href="<?= $escaper->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>"
                            data-ui-id="default-billing-edit-link"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Edit Address - shipping default')) ?>"
                        >
                            <span><?= $escaper->escapeHtml(__('Edit Address')) ?></span>
                            <?= $heroicons->arrowRightHtml('ml-2', 16, 16, ['aria-hidden' => 'true']); ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
