<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @author    Ernests Verins <info@scandiweb.com>
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<table class="flex flex-col items-start gap-5 w-fit">
    <caption>Caption text</caption>
    <caption>
        <ul>
            <li>unordered list item</li>
        </ul>
    </caption>
    <caption>
        <ul>
            <li>ordered list item</li>
        </ul>
    </caption>
    <caption>
        <a>Caption text link</a>
    </caption>
</table>
