<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @author    Ernests Verins <info@scandiweb.com>
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="flex flex-wrap gap-3">
    <div class="bg-primary text-white p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="text-base font-bold text-white">Primary</span>
        </div>
        <span class="text-sm text-white">#3690BE</span>
    </div>
    <div class="bg-primary-darker text-white p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="text-base font-bold text-white">Primary-Hover</span>
        </div>
        <span class="text-sm text-white">#2D7396</span>
    </div>
    <div class="bg-black p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="text-white font-bold">Black/text color</span>
        </div>
        <span class="text-sm text-white">#1D1F22</span>
    </div>
    <div class="bg-secondary-darker text-white p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="text-white font-bold">Border/stroke</span>
        </div>
        <span class="text-sm text-white">#A3A5AD</span>
    </div>
    <div class="bg-green text-white p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="text-white font-bold">Price</span>
        </div>
        <span class="text-sm text-white">#0D9344</span>
    </div>
    <div class="bg-primary-lighter p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="text-base font-bold">Light background</span>
        </div>
        <span class="text-sm">#F7F8F8</span>
    </div>
    <div class="bg-gray-darker p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="text-white font-bold">Dark grey</span>
        </div>
        <span class="text-sm text-white">#72757E</span>
    </div>
    <div class="bg-secondary text-white p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="font-bold">Light grey</span>
        </div>
        <span class="text-sm">#E3E3E3</span>
    </div>
    <div class="bg-green-lighter text-white p-4 w-40 flex flex-col gap-3" style="overflow-wrap: break-word;">
        <div class="flex flex-col">
            <span class="text-base font-bold w-full">Green buttons/notifications/success</span>
        </div>
        <span class="text-sm">#8BC85B</span>
    </div>
    <div class="bg-orange text-white p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="text-base font-bold">Notification/info</span>
        </div>
        <span class="text-sm">#F59E0B</span>
    </div>
    <div class="bg-red text-white p-4 w-40 flex flex-col gap-3">
        <div class="flex flex-col">
            <span class="text-white font-bold">Error</span>
        </div>
        <span class="text-sm text-white">#D1050C</span>
    </div>
</div>
