<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @author    Aleksandrs Kondratjevs <info@scandiweb.com>
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div x-data="{ isLoading: true }" class="relative max-w-80">
<?php echo $this->getLayout()
          ->createBlock('Magento\Framework\View\Element\Template')
          ->setTemplate('Magento_Theme::loader.phtml')
          ->toHtml(); ?>
</div>
