<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @author    Aleksandrs Kondratjevs <info@scandiweb.com>
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<ol>
    <li>
        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vestibulum justo a augue aliquam lobortis a eget dui. Vestibulum vel nulla pellentesque.</span>
    </li>
    <li>
        <span>Curabitur vestibulum mattis augue</span>
    </li>
    <li>
        <span>Mauris tempor scelerisque sapien, a pellentesque nibh porta in. Sed diam sapien, sollicitudin sit amet vehicula ut, sodales a magna. Etiam vestibulum vitae lacus ac varius.</span>
    </li>
</ol>
