<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @author    Aleksandrs Kondratjevs <info@scandiweb.com>
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et tristique felis, sed efficitur felis. Maecenas fermentum eleifend libero sed ornare. Integer interdum felis non diam interdum, sed sagittis lacus ultrices. Mauris vel neque ut dui cursus pulvinar et ut purus. Aliquam tincidunt sed velit id porttitor.</p>
<p>Nunc ullamcorper nibh orci, et molestie risus gravida sit amet. Integer sit amet faucibus enim. Phasellus hendrerit tempus ultrices. Etiam vitae neque non ex elementum dignissim non bibendum elit. Integer varius odio id gravida finibus.</p>
