<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @author    Aleksandrs Kondratjevs <info@scandiweb.com>
 * @copyright Copyright (c) 2024 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<ul>
    <li>
        <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</span>
    </li>
    <li>
        <span>Nulla efficitur ut justo eget faucibus. Donec lectus risus, suscipit eu gravida vel, fringilla at leo. Morbi ornare nunc eu dolor pharetra cursus. Suspendisse orci nisl, ultrices non sagittis vitae.</span>
    </li>
    <li>
        <span>Praesent sagittis dapibus nibh.</span>
    </li>
</ul>
