<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Out Of Stock Notifications Hyva Compatibility
 */

declare(strict_types=1);

/**
 * This block cannot be removed or overridden via XML layout updates
 * because it is programmatically created by the ExtendedProduct class
 * if it does not already exist.
 *
 * vendor/amasty/module-out-of-stock-hyva-compatibility/Plugins/Catalog/Block/Product/AbstractProduct.php
 */
