<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaIcons */
$hyvaIcons = $viewModels->require(SvgIcons::class);
?>
<script>
    function initQuickshopTierPrices(productId, initialTierPriceData, lowestBasePriceVariantPrice) {
        return {
            activeProductsPriceData: false,
            open: true,
            tierPriceData: initialTierPriceData,
            variantTierPriceData: initialTierPriceData,
            variantBasePrice: lowestBasePriceVariantPrice || 0,
            productWeight: 0,

            updateGrandTotal() {
                let grandTotal = 0;
                let totalSaved = 0;
                let discountPercentage = 0;
                let totalBags = 0;
                let totalWeight = 0;
                const finalPrice = this.variantBasePrice;

                // Calculate total selected bags
                this.tierPriceData.forEach((tierData, index) => {
                    const bagCount = tierData.qty;
                    const qty = parseInt(document.getElementById('quickshop_qty_' + index).value) || 0;

                    totalBags += qty * bagCount;
                    totalWeight += this.productWeight * (qty * bagCount);
                });

                // Find the best discount based on the total bags
                let bestDiscount = 0;
                this.tierPriceData.forEach((tierData) => {
                    if (totalBags >= tierData.qty) {
                        let discount = 0;

                        discount = 1 - (tierData.basePrice / finalPrice);
                        bestDiscount = Math.max(bestDiscount, discount);
                    }
                });

                // Apply the best discount across all rows and update grand total
                this.tierPriceData.forEach((tierData, index) => {
                    const bagCount = tierData.qty;
                    let pricePerItem, discount;

                    discount = Math.max(bestDiscount, 1 - (tierData.basePrice / finalPrice));
                    pricePerItem = finalPrice * (1 - discount);

                    const qty = parseInt(document.getElementById('quickshop_qty_' + index).value) || 0;
                    const rowTotal = qty > 0 ? qty * bagCount * pricePerItem : bagCount * pricePerItem;

                    // Update Price/Item and Total for each row
                    document.getElementById('quickshop_price_' + index).innerText = hyva.formatPrice(pricePerItem);
                    document.getElementById('quickshop_total_' + index).innerText = hyva.formatPrice(rowTotal);

                    // Only add to grand total if the row has a non-zero quantity
                    if (qty > 0) {
                        grandTotal += rowTotal;
                        const fullPriceTotal = finalPrice * qty * bagCount;

                        totalSaved += fullPriceTotal - rowTotal;
                        discountPercentage = Math.max(discountPercentage, discount * 100);
                    }

                    const roundedDiscount = (discount * 100).toFixed(0);

                    document.getElementById('quickshop_discount_' + index).innerText = ' -' + roundedDiscount + '%';
                });

                const mainProductQty = document.getElementById(`qty[${productId}]`);

                if (mainProductQty) {
                    mainProductQty.value = totalBags || 1;
                }

                const grandTotalElement = document.getElementById('grandTotalQuickshop');
                const percentageElement = document.getElementById('percentageDataQuickshop');

                if (!totalBags) {
                    grandTotalElement.innerText = '-';
                    percentageElement.style.display = 'none';
                } else {
                    grandTotalElement.innerText = hyva.formatPrice(grandTotal);
                    percentageElement.style.display = 'block';
                }

                document.getElementById('totalSavedQuickshop').innerText = hyva.formatPrice(totalSaved);
                document.getElementById('discountPercentageQuickshop').innerText = discountPercentage.toFixed(0);

                const totalPalletCount = totalWeight >= 65 ? Math.ceil(totalWeight / 1210) : 0;

                const palletCountTotalWrapper = document.getElementById('palletCountTotalWrapperQuickshop');
                const totalPalletCountElement = document.getElementById('totalPalletCountQuickshop');

                if (totalPalletCount > 0) {
                    totalPalletCountElement.innerText = totalPalletCount;
                    palletCountTotalWrapper.style.display = 'flex';
                } else {
                    palletCountTotalWrapper.style.display = 'none';
                }
            },

            updateTotal(index, pricePerItem, bagCount) {
                const qtyField = document.getElementById('quickshop_qty_' + index);
                const qty = !!qtyField ? parseInt(qtyField.value) : 0;
                const total = qty > 0 ? qty * bagCount * pricePerItem : bagCount * pricePerItem;

                document.getElementById('quickshop_total_' + index).innerText = hyva.formatPrice(total);
                this.updateGrandTotal();
            },

            stepUpQty(index, pricePerItem, bagCount) {
                const input = document.getElementById('quickshop_qty_' + index);

                input.stepUp();
                this.updateTotal(index, pricePerItem, bagCount);
            },

            stepDownQty(index, pricePerItem, bagCount) {
                const input = document.getElementById('quickshop_qty_' + index);

                input.stepDown();
                this.updateTotal(index, pricePerItem, bagCount);
            },

            disableMainProductQty() {
                const mainProductQty = document.getElementById(`qty[${productId}]`);
                const qtyButtons = mainProductQty.closest('.product-qty-wrapper')?.querySelector('.product-qty-buttons');
                const productTotalPriceWrapper = document.getElementById('productTotalPriceWrapperQuickhop');
                const palletCountTotalWrapper = document.getElementById('palletCountTotalWrapperQuickshop');
                const totalPalletCountElement = document.getElementById('totalPalletCountQuickshop');

                if (mainProductQty && !!this.variantTierPriceData.length) {
                    mainProductQty.style.pointerEvents = 'none';
                    mainProductQty.style.cursor = 'not-allowed';

                    if (qtyButtons) {
                        qtyButtons.style.display = 'none';
                    }

                    if (productTotalPriceWrapper) {
                        productTotalPriceWrapper.style.display = 'block';
                    }

                    if (
                      palletCountTotalWrapper &&
                      totalPalletCountElement &&
                      totalPalletCountElement.innerText !== '0'
                    ) {
                        palletCountTotalWrapper.style.display = 'block';
                    }
                } else if (mainProductQty) {
                    mainProductQty.style.pointerEvents = 'auto';
                    mainProductQty.style.cursor = 'text';

                    if (qtyButtons) {
                        qtyButtons.style.removeProperty('display');
                    }

                    if (productTotalPriceWrapper) {
                        productTotalPriceWrapper.style.display = 'none';
                    }

                    if (palletCountTotalWrapper) {
                        palletCountTotalWrapper.style.display = 'none';
                    }
                }
            },

            updateTierPriceTable() {
                const tierPrices = this.tierPriceData;
                const tableBody = document.querySelector('#tierPriceTableQuickshop tbody');
                tableBody.innerHTML = '';

                if (tierPrices?.length > 0) {
                    tierPrices.forEach((tierPrice, index) => {
                        const pricePerItem = tierPrice.basePrice;
                        const total = tierPrice.qty * pricePerItem;

                        const row = document.createElement('tr');
                        row.className = 'relative border-t border-primary';
                        row.innerHTML = `
                            <td class="py-2 pb-8 sm:pb-2">
                                <div x-data="{ qty: 0 }" class="product-cart-quantity flex flex-col sm:flex-row">
                                    <div class="product-qty-wrapper grid items-center w-[80px] h-[52px] bg-white border-2">
                                        <label for="quickshop_qty_${index}" class="sr-only"><?= $escaper->escapeHtml(__('Quantity')) ?></label>
                                        <input
                                            name="qty"
                                            id="quickshop_qty_${index}"
                                            type="number"
                                            value="0"
                                            min="0"
                                            class="form-input pl-4 py-[10px] pr-2 text-center w-full font-semibold border-0"
                                            @change="updateTotal(${index}, ${pricePerItem}, ${tierPrice.qty})"
                                            @input="$dispatch('update-qty-${productId}', qty * ${tierPrice.qty})"
                                        >
                                        <div class="product-qty-buttons flex flex-col justify-between">
                                            <button
                                                type="button"
                                                class="up hover:bg-sky-blue"
                                                @click="
                                                   qty++;
                                                   $dispatch('update-qty-${productId}', qty * ${tierPrice.qty});
                                                   stepUpQty(${index}, ${pricePerItem}, ${tierPrice.qty})
                                                "
                                            >
                                                <?= $hyvaIcons->renderHtml('up', '', 12, 12) ?>
                                            </button>
                                            <button
                                                type="button"
                                                class="down hover:bg-sky-blue"
                                                @click="
                                                   qty = Math.max(0, qty - 1);
                                                   $dispatch('update-qty-${productId}', qty * ${tierPrice.qty});
                                                   stepDownQty(${index}, ${pricePerItem}, ${tierPrice.qty})
                                                "
                                            >
                                                <?= $hyvaIcons->renderHtml('down', '', 12, 12) ?>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="flex flex-row items-center mt-1 sm:flex-col absolute top-[53px] sm:relative sm:top-0 sm:items-start sm:mt-0 sm:ml-3">
                                        <span class="block mt-2 text-sm">${tierPrice.qty} pose(r)</span>
                                        <span id="palletCount_${index}" class="block ml-1 mt-2 text-xs text-primary-lighter sm:ml-0 sm:mt-0">
                                            ${(this.productWeight * tierPrice.qty) >= 65 ?
                                              Math.ceil((this.productWeight * tierPrice.qty) / 1210) + ' <?= $escaper->escapeJs(__('pallet(s)')) ?>'
                                              : ''}
                                        </span>
                                    </div>
                                </div>
                            </td>
                            <td class="py-2">
                                <div class="flex flex-col pb-7 sm:pb-0">
                                    <span class="text-sm font-extrabold price-item" id="quickshop_price_${index}">
                                        ${hyva.formatPrice(pricePerItem)}
                                    </span>
                                    <span class="text-green text-xs discount-item">
                                        <?= $escaper->escapeHtml(__('save')) ?>
                                        <span class="text-green" id="quickshop_discount_${index}">
                                            -${tierPrice.percentage}%
                                        </span>
                                    </span>
                                </div>
                            </td>
                            <td class="py-2 text-sm text-right font-extrabold align-top">
                                <span class="block mt-2" id="quickshop_total_${index}">
                                    ${hyva.formatPrice(total.toFixed(2))}
                                </span>
                            </td>
                        `;
                        tableBody.appendChild(row);
                    });
                }

                this.disableMainProductQty();
            },

            init() {
                this.updateTierPriceTable();
            },

            eventListeners: {
                [`@update-prices-${productId}.window`](event) {
                    this.variantBasePrice = event.detail.basePrice.amount;
                    this.productWeight = event.detail.optionWeight;
                    this.activeProductsPriceData = event.detail;
                    this.variantTierPriceData = event.detail.tierPrices || [];
                    this.tierPriceData = event.detail.tierPrices || initialTierPriceData;

                    const mainProductQty = document.getElementById(`qty[${productId}]`);

                    if (mainProductQty) {
                        mainProductQty.value = 0;
                    }

                    // Reset total price and pallet count display
                    const grandTotalElement = document.getElementById('grandTotalQuickshop');
                    const totalSavedElement = document.getElementById('totalSavedQuickshop');
                    const percentageElement = document.getElementById('percentageDataQuickshop');
                    const palletCountTotalWrapper = document.getElementById('palletCountTotalWrapperQuickshop');
                    const totalPalletCountElement = document.getElementById('totalPalletCountQuickshop');
                    const productPriceBox = document.getElementById('productPriceBoxQuickshop');

                    if (this.variantTierPriceData.length) {
                        grandTotalElement.innerText = '-';
                        totalSavedElement.innerText = hyva.formatPrice(0);
                        percentageElement.style.display = 'none';
                        palletCountTotalWrapper.style.display = 'none';
                        productPriceBox.style.display = 'none';
                        totalPalletCountElement.innerText = '0';

                        document.getElementById('priceHeaderQuickshop').innerText =
                          '<?= $escaper->escapeHtml(__('Price/Item')) ?>';
                    } else {
                        document.getElementById('priceHeaderQuickshop').innerText =
                          '<?= $escaper->escapeHtml(__('Price from/Item')) ?>';
                        productPriceBox.style.display = 'block';
                    }

                    this.updateTierPriceTable();
                }
            },
        }
    }
</script>
