<div class="relative bg-blue-900 py-24 px-8">
    <div class="max-w-lg mx-auto flex flex-col gap-10">
        <div class="text-4xl leading-10 font-bold text-white drop-shadow-lg text-center md:text-6xl lg:text-7xl">
            Excuses don’t burn calories
        </div>
        <div class="text-2xl leading-8 font-semibold text-white text-center">
            Make sure each work-out is better than the last with our ProFit collection.
        </div>
        <div class="flex flex-col gap-4 sm:flex-row sm:justify-center">
            <a
                href="{{store url='home'}}"
                class="bg-white text-blue-700 text-2xl font-bold px-8 py-6 shadow-md rounded-md flex justify-between
                       sm:gap-4"
            >
                <span>Shop Men</span><span>→</span>
            </a>
            <a
                href="{{store url='home'}}"
                class="bg-white text-blue-700 text-2xl font-bold px-8 py-6 shadow-md rounded-md flex justify-between
                       sm:gap-4"
            >
                <span>Shop Women</span><span>→</span>
            </a>
        </div>
    </div>
</div>
