<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Customer\Block\Form\Login\Info;
use Magento\Framework\Escaper;

/** @var Info $block */
/** @var Escaper $escaper */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="block-new-customer flex flex-col gap-y-2">
        <div class="block-title">
            <h2 class="text-xl md:text-2xl text-primary" role="heading"
                aria-level="2"><?= $escaper->escapeHtml(__('New Customers')) ?></h2>
        </div>
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <p class="text-lg md:text-xl font-extrabold mb-2">
                <?= $escaper->escapeHtml( __('Creating an account has many benefits:')) ?>
            </p>
            <ul class="flex flex-col gap-y-2">
                <li><?= $escaper->escapeHtml( __('check out faster')) ?></li>
                <li><?= $escaper->escapeHtml( __('keep more than one address')) ?></li>
                <li><?= $escaper->escapeHtml( __('track orders and more.')) ?></li>
            </ul>
        </div>
        <div class="flex flex-grow items-end">
            <a href="<?= $escaper->escapeUrl($block->getCreateAccountUrl()) ?>"
               class="btn btn-primary w-full"><span><?= $escaper->escapeHtml(__('Create an Account')) ?></span></a>
        </div>
    </div>
<?php endif; ?>
