<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */


use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Scandiweb\MenuOrganizer\ViewModel\MenuManager;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
/** @var MenuManager $viewModelMenuManager */
$viewModelMenuManager = $viewModels->require(MenuManager::class);
/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$uniqueId = '_' . uniqid();
$menuItems = $viewModelMenuManager->getMenuItems('main-menu');
$block->setData('cache_tags', $viewModelMenuManager->getIdentities());
?>

<nav
  x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
  @keydown.window.escape="closeMenu()"
  class="z-20 order-2 sm:order-1 lg:order-2 navigation lg:hidden"
  aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation')) ?>"
  role="navigation"
>
    <button
      x-ref="mobileMenuTrigger"
      @click="openMenu()"
      :class="{'overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full' : open}"
      type="button"
      class="flex items-center justify-center w-[52px] h-[52px] bg-primary-lighter"
      aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
      aria-haspopup="menu"
      :aria-expanded="open ? 'true' : 'false'"
      :hidden="open"
    >
        <?= $heroicons->menuHtml('p-3', 48, 48, [":class" => "{ 'hidden' : open, 'block': !open }", "aria-hidden" => "true"]) ?>
    </button>

    <div
      x-ref="mobileMenuNavLinks"
      class="fixed top-0 right-0 w-full h-full hidden flex-col bg-secondary-lighter overflow-y-auto overflow-x-hidden"
      :class="{ 'flex': open, 'hidden': !open }"
      :aria-hidden="open ? 'false' : 'true'"
      role="dialog"
      aria-modal="true"
    >
        <div class="flex z-20 justify-between items-center px-4 py-[13px] bg-secondary-lighter border-b-2 border-white">
            <div class="text-base font-extrabold text-primary uppercase" x-text="currentCategoryTitle"></div>
            <button
              @click="closeMenu()"
              class="flex justify-end self-end"
              aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
              type="button"
            >
                <?= $heroicons->xHtml('hidden', 24, 24, [":class" => "{ 'hidden' : !open, 'block': open }", "aria-hidden" => "true"]) ?>
            </button>
        </div>

        <ul
          class="flex flex-col gap-y-0.5"
          role="menu"
          aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation links')) ?>"
        >
            <?php foreach ($menuItems as $index => $itemLevel1): ?>
                <?php
                $id = $itemLevel1->getId();
                $childrens = $itemLevel1->getChildren();
                ?>

                <li
                  data-child-id="m-<?= $escaper->escapeHtmLAttr($index) ?>-main"
                  role="menuitem"
                  class="level-0 bg-white"
                >
                    <div
                      class="flex items-center transition-transform duration-150 ease-in-out transform"
                      :class="{
                            '-translate-x-full' : mobilePanelActiveId,
                            'translate-x-0' : !mobilePanelActiveId
                        }"
                    >
                        <a
                          class="flex items-center w-full px-4 py-2.5 cursor-pointer no-underline text-primary text-sm"
                          href="<?= $escaper->escapeUrl($viewModelMenuManager->getFullUrl($itemLevel1)) ?>"
                          title="<?= $escaper->escapeHtmlAttr($itemLevel1->getTitle()) ?>"
                          aria-label="<?= $escaper->escapeHtmlAttr($itemLevel1->getTitle()) ?>"
                        >
                            <?= $escaper->escapeHtml($itemLevel1->getTitle()) ?>
                        </a>
                        <?php if ($itemLevel1->hasChildren()): ?>
                            <button
                              @click="openSubcategory('m-<?= /* @noEscape */ $index ?>', '<?= $escaper->escapeHtmlAttr($itemLevel1->getTitle()) ?>')"
                              class="absolute right-0 flex items-center justify-center mr-2 w-11 h-11 cursor-pointer"
                              aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories', $itemLevel1->getTitle())) ?>"
                              aria-haspopup="true"
                              :aria-expanded="mobilePanelActiveId === 'm-<?= /* @noEscape */ (string) $index ?>'"
                            >
                                <?= $hyvaicons->renderHtml('chevron', '-rotate-90', 13, 13, ["aria-hidden" => "true"]) ?>
                            </button>
                        <?php endif; ?>
                    </div>

                    <?php if ($itemLevel1->hasChildren()): ?>
                        <div
                          data-child-id="m-<?= $escaper->escapeHtmLAttr($index) ?>"
                          class="absolute top-0 right-0 z-10 flex flex-col w-full h-full bg-secondary-lighter"
                          :class="{
                                'hidden': mobilePanelActiveId !== 'm-<?= /* @noEscape */ (string) $index ?>'
                            }"
                          data-index="m-<?= htmlspecialchars((string) $index, ENT_QUOTES, 'UTF-8') ?>"
                          :aria-hidden="mobilePanelActiveId !== $el.dataset.index ? 'true' : 'false'"
                        >
                            <ul
                              class="mt-[52px] transition-transform duration-200 ease-in-out translate-x-full transform bg-white"
                              :class="{
                                    'translate-x-full' : mobilePanelActiveId !== 'm-<?= /* @noEscape */ (string) $index ?>',
                                    'translate-x-0' : mobilePanelActiveId === 'm-<?= /* @noEscape */ (string) $index ?>',
                                }"
                              role="menu"
                              aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>"
                            >
                                <!-- Back to Main Menu button -->
                                <li class="bg-secondary-lighter h-[52px]">
                                    <button
                                      type="button"
                                      class="flex relative z-20 items-center ml-1.5 px-4 py-2.5 cursor-pointer w-full h-full border-b-2 border-white"
                                      @click="backToMainCategories('m-<?= /* @noEscape */ $index ?>-main')"
                                      aria-label="<?= $escaper->escapeHtmlAttr(__('Back to main categories')) ?>"
                                    >
                                        <?= $hyvaicons->renderHtml('chevron', 'rotate-90', 12, 12, ["aria-hidden" => "true"]) ?>
                                        <span class="ml-3.5 text-sm font-extrabold">
                                            <?= $escaper->escapeHtml(__('Back to Main Menu')) ?>
                                        </span>
                                    </button>
                                </li>

                                <!-- Conditional Back to Second Level button -->
                                <li class="bg-secondary-lighter h-[52px]" x-show="mobilePanelActiveId2">
                                    <button
                                      type="button"
                                      class="flex relative z-20 items-center ml-1.5 px-4 py-2.5 cursor-pointer w-full border-b-2 h-full border-white"
                                      @click="backToSecondLevel('m-<?= /* @noEscape */ $index ?>-main')"
                                      aria-label="<?= $escaper->escapeHtmlAttr(__('Back to second level')) ?>"
                                    >
                                        <?= $hyvaicons->renderHtml('chevron', 'rotate-90', 12, 12, ["aria-hidden" => "true"]) ?>
                                        <span class="ml-3.5 text-sm font-extrabold" x-text="'<?= $escaper->escapeHtml(__('Back to')) ?> ' + secondLevelTitle"></span>
                                    </button>
                                </li>

                                <li class="relative bg-white border-b-2 border-secondary-lighter flex">
                                    <a
                                      href="<?= $escaper->escapeUrl($viewModelMenuManager->getFullUrl($itemLevel1)) ?>"
                                      title="<?= $escaper->escapeHtmlAttr($itemLevel1->getTitle()) ?>"
                                      class="relative block z-10 w-full px-4 py-3.5 cursor-pointer text-sm"
                                      aria-label="<?= $escaper->escapeHtmlAttr(__('View all %1', $itemLevel1->getTitle())) ?>"
                                    >
                                        <?= $escaper->escapeHtml(__('View all %1', $itemLevel1->getTitle())) ?>
                                    </a>
                                    <?= $heroicons->arrowHtml('absolute top-3 right-4', 24, 24, ["aria-hidden" => "true"]) ?>
                                </li>

                                <?php foreach ($childrens as $index2 => $itemLevel2): ?>
                                    <?php $grandChildren = $itemLevel2->getChildren(); ?>
                                    <li
                                      data-child-id="m-<?= $escaper->escapeHtmLAttr($index . '-' . $index2) ?>"
                                      class="level-1 bg-white border-b-2 border-secondary-lighter"
                                      role="menuitem"
                                    >
                                        <div
                                          class="flex items-center transition-transform duration-150 ease-in-out transform"
                                          :class="{
                                                '-translate-x-full' : mobilePanelActiveId2,
                                                'translate-x-0' : !mobilePanelActiveId2
                                            }"
                                        >
                                            <a
                                              class="flex items-center w-full px-4 py-2.5 cursor-pointer level-1 no-underline text-primary text-sm"
                                              href="<?= $escaper->escapeUrl($viewModelMenuManager->getFullUrl($itemLevel2)) ?>"
                                              title="<?= $escaper->escapeHtmlAttr($itemLevel2->getTitle()) ?>"
                                              aria-label="<?= $escaper->escapeHtmlAttr($itemLevel2->getTitle()) ?>"
                                            >
                                                <?= $escaper->escapeHtml($itemLevel2->getTitle()) ?>
                                            </a>
                                            <?php if ($itemLevel2->hasChildren()): ?>
                                                <button
                                                  @click="openSubSubcategory('m-<?= /* @noEscape */ $index . '-' . $index2 ?>', '<?= $escaper->escapeHtmlAttr($itemLevel2->getTitle()) ?>')"
                                                  class="absolute right-0 flex items-center justify-center w-6 h-6 mr-4 cursor-pointer bg-container-lighter border-container"
                                                  aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories', $itemLevel2->getTitle())) ?>"
                                                  aria-haspopup="true"
                                                  :aria-expanded="mobilePanelActiveId2 === 'm-<?= /* @noEscape */ $index . '-' . $index2 ?>'"
                                                >
                                                    <?= $hyvaicons->renderHtml('chevron', '-rotate-90', 12, 12, ["aria-hidden" => "true"]) ?>
                                                </button>
                                            <?php endif; ?>
                                        </div>

                                        <?php if ($itemLevel2->hasChildren()): ?>
                                            <div
                                              data-child-id="m-<?= $escaper->escapeHtmLAttr($index . '-' . $index2) ?>"
                                              class="absolute top-0 right-0 z-10 flex flex-col w-full h-full bg-secondary-lighter"
                                              :class="{
                                                    'hidden': mobilePanelActiveId2 !== 'm-<?= /* @noEscape */ $index . '-' . $index2 ?>'
                                                }"
                                              data-index-pair="m-<?= htmlspecialchars($index . '-' . $index2, ENT_QUOTES, 'UTF-8') ?>"
                                              :aria-hidden="mobilePanelActiveId2 !== $el.dataset.indexPair ? 'true' : 'false'"
                                            >
                                                <ul
                                                  class="mt-[104px] transition-transform duration-200 ease-in-out translate-x-full transform"
                                                  :class="{
                                                        'translate-x-full' : mobilePanelActiveId2 !== 'm-<?= /* @noEscape */ $index . '-' . $index2 ?>',
                                                        'translate-x-0' : mobilePanelActiveId2 === 'm-<?= /* @noEscape */ $index . '-' . $index2 ?>',
                                                    }"
                                                  role="menu"
                                                  aria-label="<?= $escaper->escapeHtmlAttr(__('Third level subcategories')) ?>"
                                                >
                                                    <li class="relative bg-white border-b-2 border-secondary-lighter flex">
                                                        <a
                                                          href="<?= $escaper->escapeUrl($viewModelMenuManager->getFullUrl($itemLevel2)) ?>"
                                                          title="<?= $escaper->escapeHtmlAttr($itemLevel2->getTitle()) ?>"
                                                          class="relative block z-10 w-full px-4 py-3.5 cursor-pointer text-sm"
                                                          aria-label="<?= $escaper->escapeHtmlAttr(__('View all %1', $itemLevel2->getTitle())) ?>"
                                                        >
                                                            <?= $escaper->escapeHtml(__('View all %1', $itemLevel2->getTitle())) ?>
                                                        </a>
                                                        <?= $heroicons->arrowHtml('absolute top-3 right-4', 24, 24, ["aria-hidden" => "true"]) ?>
                                                    </li>
                                                    <!-- Iterate through third level items -->
                                                    <?php foreach ($grandChildren as $itemLevel3): ?>
                                                        <li class="relative bg-white border-b-2 border-secondary-lighter" role="menuitem">
                                                            <a
                                                              href="<?= $escaper->escapeUrl($viewModelMenuManager->getFullUrl($itemLevel3)) ?>"
                                                              title="<?= $escaper->escapeHtmlAttr($itemLevel3->getTitle()) ?>"
                                                              class="relative z-10 block w-full px-4 py-2.5 cursor-pointer no-underline text-primary text-sm"
                                                              aria-label="<?= $escaper->escapeHtmlAttr($itemLevel3->getTitle()) ?>"
                                                            >
                                                                <?= $escaper->escapeHtml($itemLevel3->getTitle()) ?>
                                                            </a>
                                                            <?= $heroicons->arrowHtml('absolute top-2 right-4', 24, 24, ["aria-hidden" => "true"]) ?>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            </div>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            <li class="bg-white flex" role="menuitem" x-show="!mobilePanelActiveId && !mobilePanelActiveId2">
                <div class="mb-6 pl-4 pt-2.5"><?= $heroicons->infoHtml('', 24, 24, ["aria-hidden" => "true"]) ?></div>
                <div class="flex grow items-center transition-transform duration-150 ease-in-out transform">
                    <a
                      class="flex flex-col z-10 items-start w-full pl-3 pr-4 py-2.5 cursor-pointer no-underline text-primary text-sm"
                      href="/kundecenter"
                      aria-label="<?= $escaper->escapeHtmlAttr(__('Help')) ?>"
                    >
                        <span><?= $escaper->escapeHtml(__('Help')) ?></span>
                        <span class="text-xs text-primary-lighter font-normal">
                            <?= $escaper->escapeHtml(__('Explore help information')) ?>
                        </span>
                    </a>
                    <button class="absolute right-0 flex items-baseline justify-center pt-2.5 mr-2 w-11 h-11 cursor-pointer">
                        <?= $hyvaicons->renderHtml('chevron', '-rotate-90', 13, 13, ["aria-hidden" => "true"]) ?>
                    </button>
                </div>
            </li>
        </ul>
    </div>
</nav>

<script>
    'use strict';

    const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            mobilePanelActiveId: null,
            mobilePanelActiveId2: null,
            secondLevelTitle: '',
            open: false,
            currentCategoryTitle: 'Browse Categories',

            openMenu() {
                this.open = true;
                this.$nextTick(() => hyva.trapFocus(this.$refs['mobileMenuNavLinks']));
                document.body.style.position = 'fixed';
                const chatWidget = document.getElementById('bai-cb-container');

                if (chatWidget) {
                    chatWidget.style.display = 'none';
                }
            },
            closeMenu() {
                document.body.style.position = '';
                this.currentCategoryTitle = 'Browse Categories';
                if (this.open) {
                    this.$nextTick(() => this.$refs['mobileMenuTrigger'].focus() || hyva.releaseFocus());
                }
                this.open = false;
                this.mobilePanelActiveId = null;
                this.mobilePanelActiveId2 = null;
                this.secondLevelTitle = '';

                const chatWidget = document.getElementById('bai-cb-container');

                if (chatWidget) {
                    chatWidget.style.display = 'block';
                }
            },
            openSubcategory(index, title) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']');
                this.mobilePanelActiveId = this.mobilePanelActiveId === index ? 0 : index;
                this.currentCategoryTitle = title;
                this.$nextTick(() => hyva.trapFocus(menuNodeRef));
            },
            openSubSubcategory(index, title) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']');
                this.mobilePanelActiveId2 = this.mobilePanelActiveId2 === index ? 0 : index;
                this.secondLevelTitle = this.currentCategoryTitle;
                this.currentCategoryTitle = title;
                this.$nextTick(() => hyva.trapFocus(menuNodeRef));
            },
            backToMainCategories(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']');
                this.mobilePanelActiveId = 0;
                this.mobilePanelActiveId2 = 0;
                this.currentCategoryTitle = 'Browse Categories';
                this.$nextTick(() => {
                    hyva.trapFocus(this.$refs['mobileMenuNavLinks']);
                    menuNodeRef.querySelector('a').focus();
                });
            },
            backToSecondLevel(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']');
                this.mobilePanelActiveId2 = 0;
                this.currentCategoryTitle = this.secondLevelTitle;
                this.$nextTick(() => hyva.trapFocus(menuNodeRef));
            }
        }
    }
</script>
