<div class="relative h-[600px] sm:h-[500px] md:h-[400px]">
    <img class="absolute w-full md:w-1/2 h-full object-cover"
         alt="Tennis player laying on the court."
         src="https://unsplash.com/photos/F7D7oWb8aO0/download?force=true&auto=format&fit=crop&w=1200&q=80"
         width="1200"
         height="800"
         loading="lazy"
    />
    <img class="hidden md:block absolute right-0 w-1/2 h-full object-cover"
         alt="Tennis racket on the tennis field."
         src="https://unsplash.com/photos/uZmr0wwfHNA/download?force=true&auto=format&fit=crop&w=600&q=80"
         width="600"
         height="600"
         loading="lazy"
    />
    <div class="absolute bottom-0 w-full p-6 pt-28 bg-gradient-to-t to-transparent from-gray-800/75">
        <div class="mb-2 text-white text-6xl leading-none font-bold">
            Hit the court in style.
        </div>
        <a
            href="{{store url='home'}}"
            class="text-white text-2xl leading-8 font-semibold"
        >
            Shop our tennis gear →
        </a>
    </div>
</div>
