<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$imageUrl = 'https://unsplash.com/photos/F7D7oWb8aO0/download?force=true&auto=format&fit=crop&w=1200&q=80';
// Or, get an image from `web/images/` in your theme:
// $imageUrl = $escaper->escapeHtmlAttr($block->getViewFileUrl('images/banner.jpg'));
?>
<div class="relative my-2 h-[600px] sm:h-[500px] md:h-[400px]">
    <img class="absolute w-full h-full object-cover"
         alt="Hit the court in style"
         src="<?= $escaper->escapeHtmlAttr($imageUrl) ?>"
         width="1200"
         height="800"
         loading="lazy"
    />
    <div class="absolute bottom-0 w-full p-6 pt-28 bg-gradient-to-t to-transparent from-gray-800/75">
        <div class="mb-2 text-white text-6xl leading-none font-bold">
            Hit the court in style.
        </div>
        <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="block text-white text-2xl leading-8 font-semibold"
        >
            Shop our tennis gear →
        </a>
    </div>
</div>
